workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
      groups:
        - google_credentials # Add your Firebase/Google credentials group
      vars:
        PACKAGE_NAME: "com.example.subscription_alert" # Update with your package name
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK (debug)
        script: |
          flutter build apk --debug
      - name: Build APK (release)
        script: |
          flutter build apk --release
      - name: Build App Bundle (release)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic # Update with your App Store Connect API key name
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple_credentials # Add your Apple credentials group
      vars:
        APP_ID: "com.example.subscriptionAlert" # Update with your bundle ID
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS (ipa)
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  web-workflow:
    name: Web Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/web/**

  windows-workflow:
    name: Windows Build
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Windows
        script: |
          flutter build windows --release
    artifacts:
      - build/windows/**/*.exe
      - build/windows/**/*.msix
