// File generated by FlutterFire CLI.
// This is a placeholder file. You need to configure Firebase for your project.
// 
// To generate this file with your actual Firebase configuration:
// 1. Install Firebase CLI: npm install -g firebase-tools
// 2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 3. Run: flutterfire configure
//
// For more information, see: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these values with your actual Firebase configuration
  // Get these values from the Firebase Console after creating your project
  // Run: flutterfire configure
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YVK7nO0shQ9BwCmeCw34lfaDjg4d3yY',
    appId: '1:537197819060:web:dd13075a5a6a738cce53e1',
    messagingSenderId: '537197819060',
    projectId: 'subscriptionalert-f5302',
    authDomain: 'subscriptionalert-f5302.firebaseapp.com',
    storageBucket: 'subscriptionalert-f5302.firebasestorage.app',
    measurementId: 'G-ECT7SE1B95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YVK7nO0shQ9BwCmeCw34lfaDjg4d3yY',
    appId: '1:537197819060:web:dd13075a5a6a738cce53e1',
    messagingSenderId: '537197819060',
    projectId: 'subscriptionalert-f5302',
    storageBucket: 'subscriptionalert-f5302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YVK7nO0shQ9BwCmeCw34lfaDjg4d3yY',
    appId: '1:537197819060:web:dd13075a5a6a738cce53e1',
    messagingSenderId: '537197819060',
    projectId: 'subscriptionalert-f5302',
    storageBucket: 'subscriptionalert-f5302.firebasestorage.app',
    iosBundleId: 'com.example.subscriptionAlert',
  );
}
